Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip: "192.168.56.2"
  config.vm.hostname = "control-node"
  config.vm.synced_folder "./ansible", "/ansible"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "control-node"
    vb.memory = "2024"
    vb.cpus = 2
  end
  config.vm.provision "shell", path: "provision.sh"
end